### ISSUE TITLE
Egg files contain nan values

### ISSUE THREAD

**Issue by castielblak** [HoME-Platform/home-platform#20]
After the conversion process of .obj files to .egg and .bam format, there are 3023 files which could not be converted to .bam

[All the errors](https://github.com/HoME-Platform/home-platform/files/1695368/nan_errors.log) were produced because of nan values in .egg files.

**Comment by jbdel** [comment]
launch the conversion script again until there is no error

**Comment by castielblak** [comment]
@jbdel You can look into a convert_sunch.sh and you'll see that it skips files with generated .egg files.
So the case is that you can have .egg files generated but not .bam files at the same time, just like in this case.

**Comment by castielblak** [comment]
The problem is solved.

Few (3023 in total) original SUNCG _.obj_ files contain NaN values. **obj2egg** converter does not consider this problem and then produce _.egg_ files with NaN values. But **egg2bam** converter cannot handle NaN values thus declining to generate _.bam_ files.

[This](https://github.com/HoME-Platform/home-platform/pull/22) little patch should help.

**Comment by ankeshanand** [comment]
Thanks for the fix @castielblak!
