### ISSUE TITLE
Unable to create RGB buffer

### ISSUE THREAD

**Issue by srama2512** [HoME-Platform/home-platform#23]
I have tried running viewHouse.py and randomWalk.py. Both are giving the same error:
```
Exception: Unable to create RGB buffer
Segmentation fault
```
Further analysis showed that self.pipe does contain a `panda3d.core.GraphicsPipe object`. I was attempting this over ssh, but that was not the issue either. I could open other GUI based tools. Any help or suggestions regarding this will be very helpful. Thanks! 

EDIT: The operating system is Ubuntu 16.04.4 LTS

**Comment by ankeshanand** [comment]
Hi @srama2512, To view your renderings when running commands over ssh, you would need 
**indirect GLX**. I suppose the other GUI based tools you are using opening don't need to use hardware acceleration so you don't run into the same issue with them.

Indirect GLX is disabled by default on Ubuntu 15.04 and above, here's a guide that might help you enabling indirect GLX: https://www.scm.com/doc/Installation/Remote_GUI.html#ubuntu-16-04

**Comment by srama2512** [comment]
Thank you for pointing it out! Turns out that I had to install the latest version of XQuartz on my mac, which allowed me to ssh with GLX enabled. All the three samples work now.
