### ISSUE TITLE
Python 3.x supports?

### ISSUE THREAD

**Issue by gliese581gg** [HoME-Platform/home-platform#4]
Hi, thanks for great work.

I'm trying to install the library in the Python 3.5 environment but it does not work.

Do you have plans for Python 3.x support?

**Comment by ankeshanand** [comment]
@Hi gliese581gg, 
Yeah, we definitely plan to support `Python3`, and that should be out very soon. I think mostly the print statements need porting. Once we do that, and verify unit tests pass, we would be able to push it. We will update this thread as soon as that happens!

**Comment by cclauss** [comment]
See recommended changes in https://github.com/sbrodeur/evert/pull/3

**Comment by fgolemo** [comment]
@gliese581gg @ViktorM @DennisSoemers I think we got it to work now in Py3. Could you try it out please? If it looks like it's not doing what it's supposed to, please let us know in a separate issue.
